---
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
branches:
  only:
    - master
notifications:
  email: false
